### ISSUE TITLE
More colours for `ActionDigraph` `graphviz` representations

### ISSUE THREAD

**Issue by MTWhyte** [libsemigroups/libsemigroups_pybind11#100]
It would be nice to have more edge colours available for the `graphviz` representations of `ActionDigraph`. There are five colours currently available.

Rather than just extending the colour palette, I think the most robust thing to do might be to have a means of generating an arbitrary number of 'distinct' colours, perhaps via the information [here](https://stackoverflow.com/questions/470690/how-to-automatically-generate-n-distinct-colors).

On the less important aesthetic front, there's a lightweight python package called [`palettable`](https://jiffyclub.github.io/palettable/) which contains a whole load of nice-looking colour schemes (we'd want the 'qualitative' ones). This is perhaps also a viable way to add in colours -- some of these palettes have quite a lot of colours in them, and arguably we'd not be that interested in getting pictures of `ActionDigraph` instances with arbitrary large degrees.

**Comment by james-d-mitchell** [comment]
This is a great idea, I'd welcome a PR doing this!

**Comment by MTWhyte** [comment]
Better yet for contrast and accessibility are the colour schemes at https://personal.sron.nl/~pault/ (thanks to @flsmith for indirectly pointing this out)

**Comment by MTWhyte** [comment]
For reference when I make tests for this: the behaviour I find on the current `main` is:

- Where there are less than or equal to four distinct edge colours, things are coloured as expected
- Where there are five distinct edge colours, everything is coloured in black and white
- Where there are six or more distinct edge colours, an exception is thrown

It would be pretty cool to be able to catch the black and white case in a test, but I can't immediately think of how.

**Comment by james-d-mitchell** [comment]
Resolved in v0.9.0
