### ISSUE TITLE
There are still 3 instances of CI build wheels running when a release is made

### ISSUE THREAD

**Issue by james-d-mitchell** [libsemigroups/libsemigroups_pybind11#46]
There should be only one, and I think @chinmayanagpal knows how to do that, but I don't currently recall.

**Comment by chinmayanagpal** [comment]
I think this is fixed by 528b55cc56deb2c5a2e88b9f2dd9d2bc5244037b

**Comment by james-d-mitchell** [comment]
This is resolved, thanks @chinmayanagpal !
